// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin from "./routes/admin.tsx";
import * as $api_categories_index from "./routes/api/categories/index.ts";
import * as $api_products_index from "./routes/api/products/index.ts";
import * as $api_stores_id_ from "./routes/api/stores/[id].ts";
import * as $api_stores_id_auth from "./routes/api/stores/[id]/auth.ts";
import * as $api_stores_index from "./routes/api/stores/index.ts";
import * as $index from "./routes/index.tsx";
import * as $loja_store_admin_index from "./routes/loja/[store]/admin/index.tsx";
import * as $loja_store_admin_login from "./routes/loja/[store]/admin/login.tsx";
import * as $loja_store_index from "./routes/loja/[store]/index.tsx";
import * as $AdminPanelIsland from "./islands/AdminPanelIsland.tsx";
import * as $LoginIsland from "./islands/LoginIsland.tsx";
import * as $PasswordInputIsland from "./islands/PasswordInputIsland.tsx";
import * as $PlatformAdminIsland from "./islands/PlatformAdminIsland.tsx";
import * as $StorePageIsland from "./islands/StorePageIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin.tsx": $admin,
    "./routes/api/categories/index.ts": $api_categories_index,
    "./routes/api/products/index.ts": $api_products_index,
    "./routes/api/stores/[id].ts": $api_stores_id_,
    "./routes/api/stores/[id]/auth.ts": $api_stores_id_auth,
    "./routes/api/stores/index.ts": $api_stores_index,
    "./routes/index.tsx": $index,
    "./routes/loja/[store]/admin/index.tsx": $loja_store_admin_index,
    "./routes/loja/[store]/admin/login.tsx": $loja_store_admin_login,
    "./routes/loja/[store]/index.tsx": $loja_store_index,
  },
  islands: {
    "./islands/AdminPanelIsland.tsx": $AdminPanelIsland,
    "./islands/LoginIsland.tsx": $LoginIsland,
    "./islands/PasswordInputIsland.tsx": $PasswordInputIsland,
    "./islands/PlatformAdminIsland.tsx": $PlatformAdminIsland,
    "./islands/StorePageIsland.tsx": $StorePageIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
